name: run
on:
  schedule:
    - cron: '* * * * *'  # يعمل كل دقيقة لزيادة دقة تجميع الشموع وRSI
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          persist-credentials: true

      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - run: pip install requests pandas

      - name: Run python main.py
        run: python main.py
        env:
          BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
          CHAT_ID: ${{ secrets.CHAT_ID }}

      - name: Save data
        run: |
          git config --global user.name "bot"
          git config --global user.email "bot@bot.com"
          git add exness_prices.json
          git diff --staged --quiet || git commit -m "update data ${{ github.run_number }}"
          git pull --rebase origin main
          git push
